env:
  global:
    - CONAN_BUILD_REQUIRES="ninja/1.9.0"
    - CONAN_CMAKE_GENERATOR=Ninja
    - CONAN_PRINT_RUN_COMMANDS=1
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=0
    - CONAN_RUN_TESTS=1

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.8"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
      # Test detection and unit tests fail due to cross-compiling environment.
      #- <<: *linux
      #  env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=armv7hf CONAN_DOCKER_IMAGE=conanio/gcc9-armv7hf
      #- <<: *linux
      #  env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/gcc9-armv8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/gcc8
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/gcc9
      - <<: *linux
        env: CONAN_GCC_VERSIONS=10 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/gcc10
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/clang8
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=9 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/clang9
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=10 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/clang10
      - <<: *osx
        osx_image: xcode11.4
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
